#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/Lightfld/lightfield-go,github.com/stainless-sdks/lightfield-go"

REPLACEMENT="${1:-"../Lightfield-go"}"
echo "==> Replacing Go SDK with $REPLACEMENT"
go mod edit -replace github.com/Lightfld/lightfield-go="$REPLACEMENT"
go mod tidy -e
